### PR TITLE
Add movement detector device

### PR DESCRIPTION
**Pull request by kingsleyadam**
This adds a new MovementDetector device.

Initially this PR only supports the brightness level of the device, a future PR to be added to include movement events.

This addresses https://github.com/kingsleyadam/local-abbfreeathome/issues/39

### CODE REVIEW

**Comment by derjoerg** [comment]
For me it doesn't sound right to have a movement detector only have a brightness value.
The brightness value is just an additional information but the main information (the state) of this should be AL_INFO_ON_OFF. I know that this datapoint is only set, when the movement detector is paired with a switch or a light in F@H, but on the other side: Who has such a movement detector without a switch or light?

If you can also implement AL_TIMED_PRESENCE and AL_TIMED_MOVEMENT as a reference on how to "report" stateless information, it would be great

**Comment by kingsleyadam** [comment]
> For me it doesn't sound right to have a movement detector only have a brightness value. The brightness value is just an additional information but the main information (the state) of this should be AL_INFO_ON_OFF. I know that this datapoint is only set, when the movement detector is paired with a switch or a light in F@H, but on the other side: Who has such a movement detector without a switch or light?
> 
> If you can also implement AL_TIMED_PRESENCE and AL_TIMED_MOVEMENT as a reference on how to "report" stateless information, it would be great

That's next, brightness was an easy add and I just wanted to add the device. Next is to add in motion detection.

**Comment by derjoerg** [comment]
> realized it was pretty easy to update the state based on the `AL_TIMED_MOVEMENT` pairing id. I added that in.

@kingsleyadam what I saw in my previous tests was, that the datapoint AL_TIMED_MOCEMENT is always 1 and just if a movement is detected it is issued over the websocket again. Bit it never gets unset. So this is - at least from my perspective - a momentary switch and not a state. In HA this would need to emit an event. For the state of the movement detector I would say the datapoint AL_INFO_ON_OFF suits better, as it goes on and off.

**Comment by kingsleyadam** [comment]
> > realized it was pretty easy to update the state based on the `AL_TIMED_MOVEMENT` pairing id. I added that in.
> 
> @kingsleyadam what I saw in my previous tests was, that the datapoint AL_TIMED_MOCEMENT is always 1 and just if a movement is detected it is issued over the websocket again. Bit it never gets unset. So this is - at least from my perspective - a momentary switch and not a state. In HA this would need to emit an event. For the state of the movement detector I would say the datapoint AL_INFO_ON_OFF suits better, as it goes on and off.

In my tests I do see it go off.

```
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 0
```

The `AL_INFO_ON_OFF` pairingId is only listed as an input which (from my understanding) shouldn't be used to read the state of a device, but instead to interact with a device. Although I don't see why we couldn't use inputs.

**Comment by derjoerg** [comment]
Ok, perhaps I was blind 😄 

If that's the case then perfect.

**Comment by derjoerg** [comment]
> > > realized it was pretty easy to update the state based on the `AL_TIMED_MOVEMENT` pairing id. I added that in.
> > 
> > 
> > @kingsleyadam what I saw in my previous tests was, that the datapoint AL_TIMED_MOCEMENT is always 1 and just if a movement is detected it is issued over the websocket again. Bit it never gets unset. So this is - at least from my perspective - a momentary switch and not a state. In HA this would need to emit an event. For the state of the movement detector I would say the datapoint AL_INFO_ON_OFF suits better, as it goes on and off.
> 
> In my tests I do see it go off.
> 
> ```
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 1
> INFO:abbfreeathome.devices.base:Toilet Movement Detector received updated data: ABB7F59C9F7C/ch0000/odp0000: 0
> ```
> 
> The `AL_INFO_ON_OFF` pairingId is only listed as an input which (from my understanding) shouldn't be used to read the state of a device, but instead to interact with a device. Although I don't see why we couldn't use inputs.

@kingsleyadam Just to finally say a word about that: You are absolutely right. In my past tests I just didn't waited long enough. So I have a light linked to my MovementDetector and I configured that light to stay on for 30 seconds. So when I checked the MovementDetector I saw the following behaviour:
- Movement detected
-- AL_INFO_ON_OFF switched to on
-- AL_TIMED_MOVEMENT switched to on
- After 30 seconds
-- AL_INFO_ON_OFF switched to off
- After 120 seconds (and I never waited so long in the past)
-- AL_TIMED_MOVEMENT switched to off

**Pull request merged**
